language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
script:
  - cargo test --no-default-features --verbose
  - cargo test --verbose
  - cargo build --verbose --features=titlefmtr