[package]
name = "titleformat"
version = "0.1.0"
authors = ["Victor Nivet <victor@saumon.ninja>"]
description = "Metadata Title Formatting Library"
license = "MIT/Apache-2.0"

[features]
# default = ["ffmpeg"]

[dependencies]
ffmpeg = { git = "https://github.com/meh/rust-ffmpeg", rev = "28b7a82ac1ca1e201f1967b7231c21eb2e2f7447", optional = true }
nom = "3.2"

[[bin]]
name = "titleformatter"
required-features = ["ffmpeg"]