[package]
name = "titleformat"
version = "0.1.0"
authors = ["Victor Nivet <victor@saumon.ninja>"]
description = "Metadata Title Formatting Library"

[features]
# default = ["ffmpeg"]

[dependencies]
ffmpeg = { git = "https://github.com/meh/rust-ffmpeg", rev = "206ccd4e5a5c6ca5ce496ee3a6a074f21b340290", optional = true }
nom = "^3.1"

[[bin]]
name = "titleformatter"
required-features = ["ffmpeg"]