[package]
name = "titleformat"
version = "0.1.0"
authors = ["Victor Nivet <victor@saumon.ninja>"]
description = "Metadata Title Formatting Library"
license = "MIT/Apache-2.0"

[features]
# default = ["ffmpeg"]

[dependencies]
nom = { version = "^3.2", features = ["verbose-errors"] }
ffmpeg = { git = "https://github.com/meh/rust-ffmpeg", rev = "20c7ef399aa01c50eab81d87b1591ac11cd8c02c", optional = true }

[[bin]]
name = "titleformatter"
required-features = ["ffmpeg"]