[package]
name = "titleformat"
version = "0.1.0"
authors = ["Victor Nivet <victor@saumon.ninja>"]
description = "Metadata Title Formatting Library"

[features]
# default = ["ffmpeg"]

[dependencies]
ffmpeg = { git = "https://github.com/meh/rust-ffmpeg", rev = "5afe774f403fabb4903bbb8738124e6666de2ac7", optional = true }
nom = "^3.1"

[[bin]]
name = "titleformatter"
required-features = ["ffmpeg"]