[package]
name = "titleformat"
version = "0.1.0"
authors = ["Victor Nivet <victor@saumon.ninja>"]
description = "Metadata Title Formatting Library"

[features]
# default = ["ffmpeg"]

[dependencies]
ffmpeg = { git = "https://github.com/meh/rust-ffmpeg", rev = "8b4693d04c1960f7d18e6a255c3bd61b0eee180b", optional = true }
num = "0.1"
nom = "^3.1"

[[bin]]
name = "titleformatter"
required-features = ["ffmpeg"]