[package]
name = "titleformat"
version = "0.2.0"
authors = ["Victor Nivet <victor@saumon.ninja>"]
description = "Metadata Title Formatting Library"
license = "MIT/Apache-2.0"

[dependencies]
nom = "4.2.0"
id3 = { version = "0.3.0", optional = true }
metaflac = { version = "0.1.8", optional = true }

[features]
metadata_libs = ["id3", "metaflac"]
titleformatter = ["metadata_libs"]

[[bin]]
name = "titleformatter"
required-features = ["titleformatter"]